# Generated by Django 5.2.4 on 2025-08-07 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_code', models.CharField(max_length=10)),
                ('ISO2', models.CharField(max_length=2)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
