# Generated by Django 5.2.4 on 2025-08-08 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reflexo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='name',
            field=models.CharField(default='Sin nombre', max_length=255),
        ),
    ]
