# Generated by Django 5.2.4 on 2025-08-08 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reflexo', '0002_district_name'),
    ]

    operations = [
    ]
