name: Django CI

on:
  push:
    branches: [main, develop, ESTRUCTURA-DJANGO, Distritos]
  pull_request:
    branches: [main, develop, Distritos]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DJANGO_SETTINGS_MODULE: Migraciones.settings  # <- asegúrate que el nombre es correcto
      PYTHONPATH: ${{ github.workspace }}

    steps:
    
name: Checkout code
    uses: actions/checkout@v4

    
name: Set up Python
    uses: actions/setup-python@v5
    with:
      python-version: '3.11'

    
name: Install dependencies
    run: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt

    
name: Run tests with pytest
    run: |
      pytest -v -s
